#Paper: Relational Lysis and the Necessity of the Covariant Laplacian: A Structural Resolution of the Yang–Mills Mass #LinkedIn: https://www.linkedin.com/in/davidswanagon/
#Device: Apple M1 - 16GB - Series #WGR9MMW64F
#Date Run: March 03, 2026


"""
RELATIONAL LYSIS: EXPERIMENTAL VALIDATION SUITE
-------------------------------------------------------------------------------
Script Name:     exp_int_12_Script Type 41.py
Category:        5-Internal Mechanism Validation
Researcher:      Dr. David Swanagon
Original Date:   February 11, 2026
Paper Reference: Section 24.4, Proposition 24.4 (Exponential Clustering)
Theorem Support: "Asymptotic Convergence of Spectral and Spatial Mass"

-------------------------------------------------------------------------------
EXPERIMENT DESCRIPTION:
    Conducts an ultra-tight calibration between the spectral mass gap ($\sqrt{\lambda_1}$) 
    and the spatial decay constant of the field propagator. In a massive theory, 
    the Green's function must satisfy:
    $$G(r) \sim e^{-mr}$$
    
    The script explicitly compares the "Spectral Mass" ($\sqrt{\lambda_1}$) against 
    the "Lattice-Theory Mass" and a high-precision "Fitted Decay Constant" 
    extracted from the logarithmic tail of the propagator. A successful 
    unity ratio across these three distinct measurements provides empirical 
    proof that the Mass Gap generated by Relational Lysis is a physical 
    observable governing the range of interactions.

ADVERSARIAL CONDITIONS:
    - Lattice Size:             N = 800
    - Fitting Zone:             r ∈ [120, 350] (Far-field asymptotic limit)
    - Tolerance:                atol = 1e-10 (Conjugate Gradient)
    - Metric:                   Cross-Ratio of Fit, Spectral, and Lattice Mass

PASS CRITERIA:
    1. Spectral Unity:         Fit / sqrt(lambda1) ≈ 1.000xxx.
    2. Theoretical Alignment:   Fit / lattice-mass ≈ 1.000xxx.
    3. Correlation Quality:    Linear regression R^2 > 0.99999999.

USAGE:
    python3 exp_core_val_41_ultra_tight_correlation_decay.py --verbose

LICENSE:
    Proprietary Research Code - Dr. David Swanagon
-------------------------------------------------------------------------------
"""

import numpy as np
from scipy.sparse import diags
from scipy.sparse.linalg import eigsh, cg
from scipy.stats import linregress

# -------------------------------
N = 800
TAIL_START = 120
TAIL_END = 350
EPS = 1e-12


# -------------------------------
def build_laplacian(N):
    main = -2 * np.ones(N)
    off = np.ones(N - 1)
    return diags([main, off, off], [0, -1, 1], format="csr")


# -------------------------------
def spectral_gap(L):
    vals = eigsh(L, k=2, which="SM", return_eigenvectors=False)
    return abs(vals[1])


# -------------------------------
def lattice_mass(N):
    return 2 * np.sin(np.pi / (2 * N))


# -------------------------------
def green_column(L, m2):
    A = L + m2 * diags([np.ones(N)], [0])
    src = np.zeros(N)
    src[N // 2] = 1.0
    G,_ = cg(A, src, atol=1e-10)
    return G


# -------------------------------
def main():

    L = build_laplacian(N)

    lam1 = spectral_gap(L)
    m_spec = np.sqrt(lam1)
    m_lat = lattice_mass(N)

    G = np.abs(green_column(L, lam1))
    center = N // 2
    G /= G[center]

    r = np.abs(np.arange(N) - center)

    mask = (r >= TAIL_START) & (r <= TAIL_END)
    slope, _, rval, _, _ = linregress(r[mask], np.log(G[mask] + EPS))
    m_fit = -slope

    print("\nRELATIONAL LYSIS — SCRIPT TYPE 41 (ULTRA TIGHT)")
    print("Exponential Correlation Decay Test")
    print("--------------------------------------------------")
    print(f"Lattice size N:                {N}")
    print(f"sqrt(lambda1):                 {m_spec:.10f}")
    print(f"Lattice-theory mass:           {m_lat:.10f}")
    print(f"Fitted decay constant:         {m_fit:.10f}")
    print(f"Fit / sqrt(lambda1):           {m_fit/m_spec:.6f}")
    print(f"Fit / lattice-mass:            {m_fit/m_lat:.6f}")
    print(f"Correlation R^2:               {rval**2:.10f}")
    print("")

    print("Sample tail:")
    for i in [TAIL_START, 200, 300]:
        idx = center + i
        print(f"r={i:<4d}  G(r)={G[idx]:.6e}")

    print("--------------------------------------------------")
    print("INTERPRETATION:")
    print("If Fit / lattice-mass ≈ 1 and R^2 ≈ 1:")
    print("Relational Lysis produces exponential clustering.")
    print("Mass gap is physical.")


# -------------------------------
if __name__ == "__main__":
    main()
